### ISSUE TITLE
Mailcow behind Traefik

### ISSUE THREAD

**Issue by aronmgv** [jovobe/mailcow-traefik-acme-adapter#1]
Hi,

While googling how to manage to run Mailcow behind Traefik I came across your git distro. However I cannot wrap my head around.. If I may bother you for a little discussion at this topic.

Firstly let me describe my setup:
- Traefik as single and only reverse proxy running being run by docker-compose
   - it runs on host network directly, so for other docker containers I don't have problem connecting them - e.g. discourse run script does not allow you to specify which network to connect to
   - configured Let'sEncrypt
- MailCow dockerized

Initially I  had this reverse proxy for Mailcow configured via `[file]` config, basically it worked. However the cert chaining validation was failing what I recently discovered - some clients just refuse to connect via SSL/TLS or STARTTLS when this fails..

Unfortunately there still isn't official [documentation](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/) for this :/

I suppose/hope your solution addresses it. If you could point me how to set it up. Here are my setups:

### docker-compose.yml
```yml
version: '3.7'

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8081:8081
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.example.com"
      - "traefik.port=8081"
    command:
      - "--logLevel=INFO"
```
### traefik.toml
```toml
debug = false

logLevel = "INFO"

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

  [entryPoints.traefik]
    address = ":8081"
	[entryPoints.traefik.auth.basic]
    users = ["admin:XXXXXXXXXXXXXXXXXX",]

[api]
  dashboard = true
  entryPoint = "traefik"

[retry]

[web]
  address = ":8081"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "traefik.example.com"
  watch = true
  exposedByDefault = false

[acme]
  email = "admin@example.com"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  acmeLogging = true
  KeyType = "RSA4096"
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "example.com"
  sans = [
    "example.com",
    "www.example.com",
    "mail.example.com",
    "gitlab.example.com",
    "cloud.example.com",
  ]

[file]

############
# Backends #
############

[backends]

#mailcow
#  [backends.mailcow]
#    [backends.mailcow.servers.1]
#      url = "http://127.0.0.1:52180"
#      weight = 1

#netdata
  [backends.netdata]
    [backends.netdata.servers.1]
      url = "http://127.0.0.1:19999"
      weight = 1

#discourse
  [backends.discourse]
    [backends.discourse.servers.1]
      url = "http://127.0.0.1:59180"
      weight = 1

#############
# Frontends #
#############

[frontends]

#mailcow
#  [frontends.mailcow]
#    backend = "mailcow"
#    entryPoints = ["http", "https"]
#    passHostHeader = true
#	[frontends.mailcow.headers]
#	  forceSTSHeader = true
#	  STSSeconds = 315360000
#	  STSIncludeSubdomains=true
#	  STSPreload = true
#    [frontends.mailcow.routes.1]
#      rule = "Host:mail.example.com"

#netdata
  [frontends.netdata]
    backend = "netdata"
    entryPoints = ["http", "https"]
    passHostHeader = true
	basicAuth = ["admin:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",]
	[frontends.netdata.headers]
	  forceSTSHeader = true
	  STSSeconds = 315360000
	  STSIncludeSubdomains=true
	  STSPreload = true
    [frontends.netdata.routes.1]
      rule = "Host:stats.example.com"

#discourse
  [frontends.discourse]
    backend = "discourse"
    entryPoints = ["http", "https"]
    passHostHeader = true
	[frontends.discourse.headers]
	  forceSTSHeader = true
	  STSSeconds = 315360000
	  STSIncludeSubdomains=true
	  STSPreload = true
    [frontends.discourse.routes.1]
      rule = "Host:forum.example.com"
```

## Mailcow

No changes to docker-compose.. Basically running with default settings.

Appreciated, Michal
